config/routes.rb
Rails.application.routes.draw do
  get 'workouts/index'

  root to: "workouts#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :workouts, only: [:new, :show, :create, :index]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates_presence_of :exercise, :reps, :sets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    @workouts = Workout.all
  end

  def new
    @workout = Workout.new
  end

  def create
    # this can be scoped to user
    @workout = Workout.new(workout_params)
    respond_to do |format|
      if @workout.save
        format.html { redirect_to workouts_path }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end
end

private
def workout_params
  params.require(:workout).permit(:exercise, :sets, :reps, :weight)
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'application/error_messages', locals: {object: object})
  end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/application/_error_messages.html.erb
<% if object && !object.errors.empty? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this
      workout from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
  
  <h1>Workout Tracker</h1>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/workouts/index.html.erb
<%= error_messages_for(@workout) %>
<%= link_to "Track your workout", new_workout_path %>
<h1>Your Workouts</h1>

<ul class="workouts">
  <% @workouts.each do |workout| %>
    <li>
      <%= "Exercise: #{workout.exercise}" %>
      <%= "Sets: #{workout.sets}" %>
      <%= "Reps: #{workout.reps}" %>
      <%= "Weight: #{workout.weight}" %>
    </li>
  <% end %>
</ul>

app/views/workouts/new.html.erb
<%= error_messages_for(@workout) %>

<%= form_for @workout, url: workouts_path do |form| %>

  <%= form.label :exercise %>
  <%= form.text_field :exercise %>
  <%= form.label :sets %>
  <%= form.text_field :sets %>
  <%= form.label :reps %>
  <%= form.text_field :reps %>
  <%= form.label :weight %>
  <%= form.text_field :weight %>

  <%= form.submit "Submit" %>
<% end %>